### PR TITLE
First PullRequest - ESX-Speedcamera Added

### PR DESCRIPTION
**Pull request by velotoxicsounds**
Hey

I hope this time it is as desired. Since I don't have any releases on the ESX Speedcamera, I changed the link to Master for versions, the installation worked via LambetLight without any problems. If no releases are detected, it does not automatically use the master.

### CODE REVIEW

**Comment by justalemon** [comment]
Hi, when a repository doesn't have any releases, you tell the tool to use the latest 15 commits:

```
C:\Python\Python37\python.exe -m tools new
With what game does this resource works? [gtav,rdr2,common] > common
What is the name of the resource? [] > test
Who is the author of the resource? [] > test
What is the destination folder of the resource? [] > test
What other resources does this one requires? (separate them with comas) [] > 
Should this resource be updated automatically via GitHub? [y/n] > y
Who is the owner of the GitHub repository? [] > test
What is the name of the GitHub repository? [] > test
Should GitHub Releases be included? [y/n] > n
How many commits should be included? (zero to disable) [0] > 15
```

**Comment by velotoxicsounds** [comment]
Ok Thanks, i Fix it and Pull again today. Thanks

**Comment by justalemon** [comment]
@velotoxicsounds If you want, you can join the Discord server and I can explain you what each option does.

**Comment by velotoxicsounds** [comment]
I joined your Discord server, my name is RaptusLeiche772

**Pull request closed without merging**
