### PR TITLE
Revert "Added updated list of Builds for Linux and Windows systems"

### PR DESCRIPTION
**Pull request by buzs**
This reverts commit 331256277241c9f5c8dc5e52ed9d33854454bc11.

### CODE REVIEW

**Comment by justalemon** [comment]
I want to hear the why of this.

**Comment by buzs** [comment]
The previous commit removed all builds from the files.

**Comment by justalemon** [comment]
I ended up reverting the commit manually, but thanks for reporting it!

**Comment by buzs** [comment]
Apparently fivem changed the site. That's how you get the information is not working anymore.

**Pull request closed without merging**
