### PR TITLE
Added updated list of Builds for Linux and Windows systems

### PR DESCRIPTION
**Pull request by Neddings**
This is an automated process that runs daily and checks if there's an update available

### CODE REVIEW

**Comment by justalemon** [comment]
What do you mean with "automated process"?

**Comment by Neddings** [comment]
That I have setup a worker that checks if there's new builds ready and then updates the repo and hands off the Pull request :)

**Comment by justalemon** [comment]
I mean, how exactly? So it can be implemented permanently in the repo.

**Comment by Neddings** [comment]
It's a Windows task that uses wget to get both the files with a Chrome browser, then runs the convert and git commits it

**Comment by justalemon** [comment]
Weird, the last time that we tried to parse the page automatically Cloudflare locked us out:

image

(I had to release a quick update for that, so that is why we have to update the builds manually)

**Comment by justalemon** [comment]
In the future if we get access to GitHub actions we might make it a cron task.

**Pull request merged**
